#!/bin/bash
export JAVA_HOME=/opt/java/jdk1.5.0_22 
export JAVA_BINDIR=/opt/java/jdk1.5.0_22/bin 
export JAVACMD=/opt/java/jdk1.5.0_22/bin/java

JAVA_HOME=/opt/java/jre1.8.0_131 JAVA_BINDIR=/opt/java/jre1.8.0_131/bin JAVACMD=/opt/java/jre1.8.0_131/bin/java
JAVA_HOME=/opt/java/jdk1.7.0_80 JAVA_BINDIR=/opt/java/jdk1.7.0_80/bin JAVACMD=/opt/java/jdk1.7.0_80/bin/java
JAVA_HOME=/opt/java/jdk1.5.0_22 JAVA_BINDIR=/opt/java/jdk1.5.0_22/bin JAVACMD=/opt/java/jdk1.5.0_22/bin/java
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 JAVA_BINDIR=/usr/lib/jvm/java-8-openjdk-amd64/bin JAVACMD=/usr/lib/jvm/java-8-openjdk-amd64/bin/java

/usr/lib/jvm/java-8-openjdk-amd64/bin
