//tealium universal tag - utag.244 ut4.0.202103162003, Copyright 2021 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1,'link':1};u.initialized=false;u.map={};u.extend=[function(a,b){try{if(1){if(b['ut.event']=="link"&&b.component_event){var path=b.component_event.path||(b.component_event.composedPath&&b.component_event.composedPath());var link=null;var link_id=null;if(typeof b.component_event.target.getAttribute=="function"&&b.component_event.target.getAttribute("data-lid")){link_id=b.component_event.target.getAttribute("data-lid");}
if(typeof b.component_event.currentTarget.getAttribute=="function"&&b.component_event.currentTarget.getAttribute("data-lid")){link_id=b.component_event.currentTarget.getAttribute("data-lid");}
if(path){for(var i=0;i<path.length;i++){if(path[i]!==window&&path[i].nodeName.indexOf("TI-")>-1){if(path[i].getAttribute('data-lid')){link_id=path[i].getAttribute('data-lid');break;}}}
if(path[0].localName=="a"){link=path[0];}
if(!link){for(var i=0;i<path.length;i++){if(path[i]!==window&&path[i].localName=="a"){link=path[i];break;}}}}else{if(b.component_event.target.localName=="a"){link=b.component_event.target;}}
if(/^vb\|.*/.test(link_id)){b.vBundleId=link_id.split('|')[1];link_id='vb';}
if(b.component_event.type=="tiMetricsAction"){if(typeof b.component_event.detail.error!=="undefined"&&b.component_event.detail.error.length>0){b.event_category='error';b.event_action=b.component_event.detail.eventName.toLowerCase();b.event_label=b.component_event.detail.error.toLowerCase();b.event_value='1';}else{if(!link_id&&b.component_event.detail.eventName){link_id=b.component_event.detail.elementName;if(/^vb\|.*/.test(link_id)){b.vBundleId=link_id.split('|')[1];link_id='vb';}}
if(b.component_event.detail.eventName=="add to cart"){b.event_category='store';b.event_action='add to cart';b.event_label=link_id+"|"+"add to cart|"+b.component_event.detail.data.ti_opn;b.event_value='1';b.custom_metric_value='55';b.events=['add to cart'];b.ecom_event='add';b.sampleCheckoutType=b.component_event.detail.data.part_type;b.ti_opn=b.component_event.detail.data.ti_opn;b.ti_gpn=b.component_event.detail.data.ti_gpn;b._cprod=b._cprodname=[b.component_event.detail.data.ti_opn];b._cquan=[b.component_event.detail.data.part_quantity];b._cprice=[b.component_event.detail.data.part_unit_price];b._ccat=b.part_type=[b.component_event.detail.data.part_type.toUpperCase()];b._ccurrency=[b.component_event.detail.data.currency_code];b.cart_source=[b.component_event.detail.data.element_type];b.product_status=[b.component_event.detail.data.product_status];b.part_carrier=[b.component_event.detail.data.part_carrier];b.vBundleId=b.component_event.detail.data.vBundleId;}
if(b.component_event.detail.eventName=="snackbar impression"){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_non_interaction=1;b.event_label=link_id;b.event_value='1';}
if(b.component_event.detail.eventName=="hover"){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id+" "+b.component_event.detail.data.context;b.event_value='1';}
if(b.component_event.detail.eventName=="image click"){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id+" "+b.component_event.detail.data.value+" "+b.component_event.detail.data.column;b.event_value='1';}
if(b.component_event.detail.eventName=="scroll"){window.uniqueEvents=window.uniqueEvents||[];if(_isInArrayAlternative(uniqueEvents,b.component_event.detail.data.context)==false){if(_isInArrayAlternative(uniqueEvents,b.component_event.detail.eventName)==false){postToABMPPOC("scroll");uniqueEvents.push(b.component_event.detail.eventName);}
b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=b.component_event.detail.data.context.replace(' ','|');b.event_value='1';uniqueEvents.push(b.component_event.detail.data.context);}}
if(b.component_event.detail.eventName=="click"||b.component_event.detail.eventName=="link click"){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id+"|"+b.component_event.detail.data.value;b.event_value='1';}
if(b.component_event.detail.eventName=="sort"){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id+" "+b.component_event.detail.data.sortColumn+"|"+b.component_event.detail.data.sortDirection;b.event_value='1';}
if(b.component_event.detail.eventName=="tab click"){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id+" "+b.component_event.detail.data.context.toLowerCase();b.event_value='1';}
if(b.component_event.detail.eventName=="focus input"){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id+" "+b.component_event.detail.data.context.toLowerCase();b.event_value='1';}
if(b.component_event.detail.eventName=="filter"){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id+" "+b.component_event.detail.data.filterColumn+'|'+b.component_event.detail.data.filterValue;b.event_value='1';}
if(b.component_event.detail.eventName=="focus quantity input"){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id+" "+b.component_event.detail.context.toLowerCase();b.event_value='1';}
if(b.component_event.detail.eventName=="buy from distributor"){b.ti_gpn=b.component_event.detail.data.ti_gpn;b.ti_opn=b.component_event.detail.data.ti_opn;b.distributor_name=b.component_event.detail.data.distributor_name;b.sampleCheckoutType=b.component_event.detail.data.part_type;b.vBundleId=b.component_event.detail.data.vBundleId;if(typeof window.ti_addEvent=="function"){window.ti_addEvent(b,["conversion funnel","parts in carts"]);}}
if(b.component_event.detail.eventName=="chevron click"){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id+" "+b.component_event.detail.data.column.toLowerCase()+" "+b.component_event.detail.data.value.toLowerCase();b.event_value='1';}
if(b.component_event.detail.eventName.indexOf("modal close")>-1){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id;b.event_value='1';}
if(b.component_event.detail.eventName=="request sample"){b.sampleCheckoutType="sample";b.ti_opn=b.component_event.detail.data.ti_opn;b.ti_gpn=b.component_event.detail.data.ti_gpn;window.ti_addEvent(b,'sampleorbuy checkout');}
if(b.component_event.detail.eventName=="email validated"){window.ti_addEvent(b,['myti page email validated','conversion funnel']);}
if(b.component_event.detail.eventName=="custom reel selection"){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id+"|"+b.component_event.detail.context+"|"+b.component_event.detail.data.value;b.event_value='1';}
if(b.component_event.detail.eventName=="file browse"){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id;b.event_value='1';}
if(b.component_event.detail.eventName.indexOf("date code ")>-1){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id+"|"+b.component_event.detail.context+"|"+b.component_event.detail.data.value;b.event_value='1';}
if(b.component_event.detail.elementName=="TI-QUICK-ADD-TO-CART"){if(b.component_event.detail.eventName=="quick add to cart"){var express_opn=[];var express_quantity=[];var express_source=[];var express_carrier=[];var express_refnum=[];b.component_event.detail.data.partList.forEach(function(e){express_opn.push(e.OpnId);express_quantity.push(e.Quantity);express_source.push(e.TiAddtoCartSource);express_carrier.push(e.CrOption);express_refnum.push(e.CustomRefNo);});b.event_category='store';b.event_action='add to cart';b.event_label=link_id+"|"+"quick add to cart";b.event_value='1';b.custom_metric_value='55';b.events=['add to cart'];b.ecom_event='add';b._cprod=b._cprodname=express_opn;b._cquan=express_quantity;b.cart_source=express_source;}else{b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id;b.event_value='1';}}
if(b.component_event.detail.elementName.indexOf("TI-QRP")>-1){if(b.component_event.detail.eventName=="qrp results"){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id;b.event_value='1';b.search_type='qrp tool';b.search_term=b.component_event.detail.data.value.length>1?b.component_event.detail.data.value.join("|"):b.component_event.detail.data.value[0];b.events=['internal searches'];b.custom_metric_value="7";}else if(b.component_event.detail.eventName=="qrp submit"){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id;b.event_value='1';}else if(b.component_event.detail.eventName=="qrp download selected"){var loc="";if(path&&path[1].nodeName=="TD"){loc="qrp tool|results table "+b.component_event.detail.data.fileType+" "+b.component_event.detail.data.part_number[0];}else if(b['dom.pathname']=="/qrp/report"){loc="qrp report|individual part number "+b.component_event.detail.data.fileType+" "+b.component_event.detail.data.part_number[0];}else{loc="qrp tool|download selected "+b.component_event.detail.data.fileType;}
var part_list=b.component_event.detail.data.part_number.join("|");var filename=b.component_event.detail.data.part_number.length>1?"multiple":b.component_event.detail.data.part_number[0];b.tcPartNumber=part_list;b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=loc;b.event_value='1';b.events=['quality data download'];b.custom_metric_value="1";b.download_file_name="qrp-"+filename+"-"+b.component_event.detail.data.fileType;}else{b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id;b.event_value='1';}}
if(b.component_event.detail.elementName.indexOf("TI-PPAP")>-1){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=typeof b.component_event.detail.data.ppap_request_num!=="undefined"?link_id+"|"+b.component_event.detail.data.ppap_request_num:link_id;b.event_value='1';b.ti_opn=typeof b.component_event.detail.data.ti_opn!=="undefined"?b.component_event.detail.data.ti_opn:"";if(b.component_event.detail.eventName=="ppap form submit"){_tiAnalyticsTrack('decibelInsight','formSubmitted','[data-di-form-id="ppap_request"]');}}}}}}}catch(e){utag.DB(e)}},function(a,b){if(b['video_event']){if(b['video_event']=='video_start'){ti_addEvent(b,'conversion funnel');}
b['video_event']=b['video_event'].replace(/\_/g,' ');b['videoTimeStamp']=b['page_timestamp']||utag_data['page_timestamp'];ti_addEvent(b,b['video_event']);}
if(b['ev_action']&&b['ev_action'].indexOf('ab test')==-1){ti_addEvent(b,'personalization');}
if(b['link_text']&&!b['link_id']){if(b['activityPromoID']){b['promo_id']=b['activityPromoID'];ti_addEvent(b,'activity promo impression');}else if(b['homepagePromoID']){b['promo_id']=b['homepagePromoID'];ti_addEvent(b,'homepage promo impression');}else if(b['productPromoID']){b['promo_id']=b['productPromoID'];ti_addEvent(b,'product promo impression');}}
if(b['event_category']){if(b['event_category']=='links'&&b['download_file_name']){ti_addEvent(b,'file downloads');}
if(b['event_category']=='promo'&&b['event_action']&&b['event_action'].indexOf('click')>-1){ti_addEvent(b,'promo click');}
if(b['event_category']=='links'&&b['event_label']=='product_folder_samplebuy_table|request sample'){b['sampleCheckoutType']="sample";ti_addEvent(b,'sampleorbuy checkout');}
if(b['event_category']=='store'&&b['event_action']=='add to cart'){ti_addEvent(b,'add to cart');}
if(b['event_category']=='links'&&b['event_label']=='remove item'&&b['ga_page_name'].indexOf("shopping cart")>-1){ti_addEvent(b,'remove item');}}
if(b['oct_eventName']){if(b['oct_eventName']=='Link Track'){ti_addEvent(b,'custom link track');}
if(b['oct_eventName']=='selection tool link click'){ti_addEvent(b,'selection tool link click');}
if(b['oct_eventName']=='ODS Search'){ti_addEvent(b,'search type');}
if(b['oct_eventName']=='search'){if(b['search_type']&&b['search_type'].indexOf('tidesigns')>-1){ti_addEvent(b,'reference design search');}else{ti_addEvent(b,'search type');}}
if(b['oct_eventName']=='selection tool search'){ti_addEvent(b,'selection tool search');}
if(b['oct_eventName']=='null search'){ti_addEvent(b,'null search');}
if(b['oct_eventName']=='Data Converter'){ti_addEvent(b,'data converter');}
if(b['oct_eventName']=='Companion Parts'){ti_addEvent(b,'companion parts');}
}
if((b['dom.pathname'].match(/\/lsds\/ti.*/gi)!==null||b['isTrainingPortal']=='yes'||b['pageType']=="portal")&&a=='view'){utag_data['events']=ti_addEvent(b,'portal page view');}
if((b["dom.pathname"]=="/qrp/report"||b["dom.pathname"]=="/quality-reliability-packaging-download/report")&&b["ut.event"]=="view"){ti_addEvent(b,"quality data view");b.tcPartNumber=window.partNum}},function(a,b){if(!utag.onload_flag[id]&&a==="view"){utag.onload_flag[id]=1;if(document.readyState!="complete"){addLoadEvent(function(){utag.onload_flag[id]=2;utag.view(utag_data,null,[id]);});return false;}}else{if(a=="view"&&!(utag.onload_flag[id]==2&&document.readyState=="complete")){return false;}}},function(a,b){try{if(1){var clientId=/int|uat|sat/.test(utag_data['dom.domain'])?'ti_test':'ti';window._trackSF=function(){if(utag_data['js_page._metrics_store_data.store_page_type']&&(utag_data['js_page._metrics_store_data.store_page_type'].toLowerCase()=='cart'||utag_data['js_page._metrics_store_data.store_page_type'].toLowerCase()=='orderconfirmation')){var productDetails=[];for(var j=0;j<_metrics_store_data.part_number.length;j++){var detail={'name':_metrics_store_data.part_number[j],'description':_metrics_store_data.hasOwnProperty('part_description')?_metrics_store_data.part_description[j]:'','img':_metrics_store_data.hasOwnProperty('part_image_url')?_metrics_store_data.part_image_url[j]:'','url':_metrics_store_data.hasOwnProperty('part_url')?_metrics_store_data.part_url[j]:''};productDetails.push(detail);}
var type=utag_data['js_page._metrics_store_data.store_page_type'].toLowerCase()=='cart'?'shopping_cart':'purchase';sfTagManager({'clientId':clientId,'type':type,'paud':true,'parts':productDetails});}}
if(typeof b['ut.event']!=='undefined'&&b['ut.event']!='view'&&typeof b.events!=='undefined'){for(var i=0;i<b.events.length;i++){if(b.events[i]=='add to cart'){if(typeof _metrics_store_data!='undefined'){var productDetail=[{'name':_metrics_store_data.part_number,'description':_metrics_store_data.part_description||'','img':_metrics_store_data.part_image_url||'','url':_metrics_store_data.part_url||''}];sfTagManager({'clientId':clientId,'type':'shopping_cart','paud':true,parts:productDetail});}else if(b.component_event&&b.component_event.detail&&b.component_event.detail.data){var productDetail=[{'name':b.component_event.detail.data.ti_opn,'description':b.component_event.detail.data.part_description||'','img':b.component_event.detail.data.part_image_url||'','url':b.component_event.detail.data.part_url||''}];sfTagManager({'clientId':clientId,'type':'shopping_cart','paud':true,parts:productDetail});}}}}}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={"base_url":"https://t.supplyframe.com/js/track.min.js?ti"
};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){if(typeof utag_err!='undefined'){utag_err.push({e:'extension error:'+e,s:utag.cfg.path+'utag.'+id+'.js',l:c,t:'ex'})}}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
u.loader_cb=function(){if(window._trackSF){_trackSF();}
};if(!u.initialized){u.initialized=true;u.loader({"type":"script","src":u.data.base_url,"cb":u.loader_cb,"loc":"script","id":'utag_244'});}
else{}
}};utag.o[loader].loader.LOAD(id);})("244","ti.main");}catch(error){utag.DB(error);}
