(self.AMP=self.AMP||[]).push({n:"amp-bind",v:"2101211748002",m:0,f:(function(AMP,_){
'use strict';var m,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function ba(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return d}return function(){throw Error("Cannot find global object");}()}var ca=ba(this);"function"===typeof Symbol&&Symbol("x");var da;
if("function"==typeof Object.setPrototypeOf)da=Object.setPrototypeOf;else{var ea;a:{var fa={a:!0},ha={};try{ha.__proto__=fa;ea=ha.a;break a}catch(a){}ea=!1}da=ea?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ia=da;
function ja(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(ia)ia(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Ma=b.prototype};function ka(a,b){var c=b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(d){return c}};var la=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function ma(a){var b=Object.create(null);if(!a)return b;for(var c;c=la.exec(a);){var d=ka(c[1],c[1]),e=c[2]?ka(c[2].replace(/\+/g," "),c[2]):"";b[d]=e}return b};var na="";
function q(){var a=self;if(a.__AMP_MODE)var b=a.__AMP_MODE;else{b=ma(a.location.originalHash||a.location.hash);var c=ma(a.location.search);na||(na=a.AMP_CONFIG&&a.AMP_CONFIG.v?a.AMP_CONFIG.v:"012101211748002");b={localDev:!1,development:!!(0<=["1","actions","amp","amp4ads","amp4email"].indexOf(b.development)||a.AMP_DEV_MODE),examiner:"2"==b.development,esm:!1,geoOverride:b["amp-geo"],minified:!0,lite:void 0!=c.amp_lite,test:!1,log:b.log,version:"2101211748002",rtvVersion:na};b=a.__AMP_MODE=b}return b}
;var oa=Object.prototype.toString;function r(a){return a?Array.prototype.slice.call(a):[]}function v(a){return"[object Object]"===oa.call(a)};var x=self.AMP_CONFIG||{},pa=("string"==typeof x.cdnProxyRegex?new RegExp(x.cdnProxyRegex):x.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function qa(a){if(!self.document||!self.document.head||self.location&&pa.test(self.location.origin))return null;var b=self.document.head.querySelector('meta[name="'+a+'"]');return b&&b.getAttribute("content")||null}
var y={thirdParty:x.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:x.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof x.thirdPartyFrameRegex?new RegExp(x.thirdPartyFrameRegex):x.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:x.cdnUrl||qa("runtime-host")||"https://cdn.ampproject.org",cdnProxyRegex:pa,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,errorReporting:x.errorReportingUrl||"https://us-central1-amp-error-reporting.cloudfunctions.net/r",betaErrorReporting:x.betaErrorReportingUrl||
"https://us-central1-amp-error-reporting.cloudfunctions.net/r-beta",localDev:x.localDev||!1,trustedViewerHosts:[/(^|\.)google\.(com?|[a-z]{2}|com?\.[a-z]{2}|cat)$/,/(^|\.)gmail\.(com|dev)$/],geoApi:x.geoApiUrl||qa("amp-geo-api")};function ra(a){var b=Object.getOwnPropertyDescriptor(a,"message");if(b&&b.writable)return a;var c=a.stack,d=Error(a.message),e;for(e in a)d[e]=a[e];d.stack=c;return d}self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var z=self.__AMP_LOG;function A(){if(!z.user)throw Error("failed to call initLogConstructor");return z.user}function B(){if(z.dev)return z.dev;throw Error("failed to call initLogConstructor");}
function D(a,b,c,d,e){return A().assert(a,b,c,d,e,void 0,void 0,void 0,void 0,void 0,void 0)};var sa=Object.prototype.hasOwnProperty;function E(a){var b=Object.create(null);a&&Object.assign(b,a);return b}function F(a){return a||{}}function G(a,b){if(sa.call(a,b))return a[b]}
function ta(a,b){var c=[],d=[];d.push({t:a,s:b,d:0});for(a={};0<d.length;){b=d.shift();a.G=b.t;a.C=b.s;a.P=b.d;if(c.includes(a.C))throw Error("Source object has a circular reference.");c.push(a.C);a.G!==a.C&&(10<a.P?Object.assign(a.G,a.C):Object.keys(a.C).forEach(function(e){return function(f){var g=e.C[f];if(sa.call(e.G,f)){var h=e.G[f];if(v(g)&&v(h)){d.push({t:h,s:g,d:e.P+1});return}}e.G[f]=g}}(a)));a={C:a.C,G:a.G,P:a.P}}};function H(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b};function I(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return J(a,b)}function K(a,b){var c=L(a);c=M(c);return J(c,b)}function ua(a,b){a=L(a);a=M(a);return va(a,b)?J(a,b):null}function L(a){return a.nodeType?I((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function M(a){a=L(a);return a.isSingleDoc()?a.win:a}function J(a,b){va(a,b);a=N(a)[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}
function wa(a,b,c,d){var e=N(a),f=e[c];f||(f=e[c]={obj:null,promise:null,resolve:null,reject:null,context:null,ctor:null,adopted:!1});f.ctor||f.obj||(f.ctor=d,f.context=b,f.adopted=!1,f.resolve&&J(a,c))}function xa(a,b){var c=ya(a,b);if(c)return c;a=N(a);a[b]=za();return a[b].promise}function ya(a,b){var c=N(a)[b];if(c){if(c.promise)return c.promise;J(a,b);return c.promise=Promise.resolve(c.obj)}return null}function N(a){var b=a.__AMP_SERVICES;b||(b=a.__AMP_SERVICES={});return b}
function va(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor&&!a.obj)}function za(){var a=new H,b=a.promise,c=a.resolve;a=a.reject;b.catch(function(){});return{obj:null,promise:b,resolve:c,reject:a,context:null,ctor:null}};function O(){this.wa=100;this.X=this.ba=0;this.R=Object.create(null)}O.prototype.has=function(a){return!!this.R[a]};O.prototype.get=function(a){var b=this.R[a];if(b)return b.access=++this.X,b.payload};O.prototype.put=function(a,b){this.has(a)||this.ba++;this.R[a]={payload:b,access:this.X};if(!(this.ba<=this.wa)){B().warn("lru-cache","Trimming LRU cache");a=this.R;var c=this.X+1,d;for(d in a){var e=a[d].access;if(e<c){c=e;var f=d}}void 0!==f&&(delete a[f],this.ba--)}};var Aa=F({c:!0,v:!0,a:!0,ad:!0}),Ba,Ea,Fa=/[?&]amp_js[^&]*/,Ga=/[?&]amp_gsa[^&]*/,Ha=/[?&]amp_r[^&]*/,Ia=/[?&]amp_kit[^&]*/,Ja=/[?&]usqp[^&]*/;
function P(a){Ba||(Ba=self.document.createElement("a"),Ea=self.__AMP_URL_CACHE||(self.__AMP_URL_CACHE=new O));var b=Ea,c=Ba;if(b&&b.has(a))a=b.get(a);else{c.href=a;c.protocol||(c.href=c.href);var d={href:c.href,protocol:c.protocol,host:c.host,hostname:c.hostname,port:"0"==c.port?"":c.port,pathname:c.pathname,search:c.search,hash:c.hash,origin:null};"/"!==d.pathname[0]&&(d.pathname="/"+d.pathname);if("http:"==d.protocol&&80==d.port||"https:"==d.protocol&&443==d.port)d.port="",d.host=d.hostname;d.origin=
c.origin&&"null"!=c.origin?c.origin:"data:"!=d.protocol&&d.host?d.protocol+"//"+d.host:d.href;b&&b.put(a,d);a=d}return a}
function Ka(a,b){var c=void 0===c?"source":c;D(null!=a,"%s %s must be available",b,c);var d=a;"string"==typeof d&&(d=P(d));var e;(e="https:"==d.protocol||"localhost"==d.hostname||"127.0.0.1"==d.hostname)||(d=d.hostname,e=d.length-10,e=0<=e&&d.indexOf(".localhost",e)==e);D(e||/^(\/\/)/.test(a),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,a)}
function Q(a){"string"==typeof a&&(a=P(a));return y.cdnProxyRegex.test(a.origin)}
function La(a){"string"==typeof a&&(a=P(a));if(!Q(a))return a.href;var b=a.pathname.split("/");D(Aa[b[1]],"Unknown path prefix in url %s",a.href);var c=b[2],d="s"==c?"https://"+decodeURIComponent(b[3]):"http://"+decodeURIComponent(c);D(0<d.indexOf("."),"Expected a . in origin %s",d);b.splice(1,"s"==c?3:2);b=d+b.join("/");d=(d=a.search)&&"?"!=d?(d=d.replace(Fa,"").replace(Ga,"").replace(Ha,"").replace(Ia,"").replace(Ja,"").replace(/^[?&]/,""))?"?"+d:"":"";return b+d+(a.hash||"")}
function Ma(a,b){"string"==typeof b&&(b=P(b));if("function"==typeof URL)var c=(new URL(a,b.href)).toString();else{c=a;var d=b;"string"==typeof d&&(d=P(d));c=c.replace(/\\/g,"/");var e=P(c);c=c.toLowerCase().startsWith(e.protocol)?e.href:c.startsWith("//")?d.protocol+c:c.startsWith("/")?d.origin+c:d.origin+d.pathname.replace(/\/[^/]*$/,"/")+c}return c}function Na(a){var b=P(a),c=ma(b.search);D(!("__amp_source_origin"in c),"Source origin is not allowed in %s",a)};var R,Oa="Webkit webkit Moz moz ms O o".split(" ");function Pa(a){var b=!1;void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")};function Qa(){return AMP.BaseElement.apply(this,arguments)||this}ja(Qa,AMP.BaseElement);m=Qa.prototype;m.getLayoutPriority=function(){return 1};m.isAlwaysFixed=function(){return!0};m.isLayoutSupported=function(){return!0};m.renderOutsideViewport=function(){return!0};m.M=function(){return"<amp-bind-macro> "+(this.element.getAttribute("id")||"<unknown id>")};var Ra;function S(){return Ra?Ra:Ra=Promise.resolve(void 0)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var Sa=/(\0)|^(-)$|([\x01-\x1f\x7f]|^-?[0-9])|([\x80-\uffff0-9a-zA-Z_-]+)|[^]/g;function Ta(a,b,c,d,e){return e?e:b?"\ufffd":d?a.slice(0,-1)+"\\"+a.slice(-1).charCodeAt(0).toString(16)+" ":"\\"+a};function Ua(a,b){for(;a&&void 0!==a;a=a.parentElement)if(b(a))return a;return null}function Va(a,b){return a.closest?a.closest(b):Ua(a,function(c){var d=c.matches||c.webkitMatchesSelector||c.mozMatchesSelector||c.msMatchesSelector||c.oMatchesSelector;return d?d.call(c,b):!1})}function Wa(a,b){for(var c=a.length,d=0;d<c;d++)b(a[d],d)}function Xa(a){return"SCRIPT"==a.tagName&&a.hasAttribute("type")&&"APPLICATION/JSON"==a.getAttribute("type").toUpperCase()}
function Ya(a){a.tagName.startsWith("AMP-");if(a.createdCallback)return Promise.resolve(a);if(!a.__AMP_UPG_PRM){var b=new H;a.__AMP_UPG_PRM=b.promise;a.__AMP_UPG_RES=b.resolve}return a.__AMP_UPG_PRM};function Za(a){var b=ya(M(a),"bind");if(b)return b;var c=L(a);return c.waitForBodyOpen().then(function(){var d=c.win;var e=c.win.document.head;if(e){var f={};e=e.querySelectorAll("script[custom-element],script[custom-template]");for(var g=0;g<e.length;g++){var h=e[g];h=h.getAttribute("custom-element")||h.getAttribute("custom-template");f[h]=!0}f=Object.keys(f)}else f=[];return f.includes("amp-bind")?I(d,"extensions").waitForExtension(d,"amp-bind"):S()}).then(function(){var d=c.win;return d.__AMP_EXTENDED_ELEMENTS&&
d.__AMP_EXTENDED_ELEMENTS["amp-bind"]?xa(M(a),"bind"):null})}function $a(a){var b=ua(a,"bind");return b?Promise.resolve(b):Za(a)};function T(a,b){if("."==b)return a;b=b.split(".");for(var c=0;c<b.length;c++){var d=b[c];if(d&&a&&void 0!==a[d]&&(null==a||"object"!=typeof a?0:Object.prototype.hasOwnProperty.call(a,d)))a=a[d];else{a=void 0;break}}return a}function ab(a,b){try{return JSON.parse(a)}catch(c){return b&&b(c),null}}
function bb(a,b){if(!isFinite(20))throw Error("Invalid depth: 20");if(a===b)return!0;for(a=[{a:a,b:b,depth:20}];0<a.length;){var c=a.shift();b=c.a;var d=c.b;c=c.depth;if(0<c){if(typeof b!==typeof d)return!1;if(Array.isArray(b)&&Array.isArray(d)){if(b.length!==d.length)return!1;for(var e=0;e<b.length;e++)a.push({a:b[e],b:d[e],depth:c-1});continue}else if(b&&d&&"object"===typeof b&&"object"===typeof d){var f=Object.keys(b),g=Object.keys(d);if(f.length!==g.length)return!1;for(e=0;e<f.length;e++){var h=
f[e];a.push({a:b[h],b:d[h],depth:c-1})}continue}}if(b!==d)return!1}return!0};function cb(a,b,c){c=void 0===c?{}:c;var d=void 0===c.expr?".":c.expr,e=void 0===c.urlReplacement?0:c.urlReplacement,f=void 0===c.refresh?!1:c.refresh,g=void 0===c.xssiPrefix?void 0:c.xssiPrefix;Ka(b.getAttribute("src"),b);var h=I(a.win,"batched-xhr");return db(b,e,f).then(function(k){return h.fetchJson(k.xhrUrl,k.fetchOpt)}).then(function(k){return I(a.win,"xhr").xssiJson(k,g)}).then(function(k){if(null==k)throw Error("Response is undefined.");return T(k,d||".")}).catch(function(k){throw A().createError("failed fetching JSON data",
k);})}
function db(a,b,c){var d=a.getAttribute("src"),e=ua(a,"url-replace");return(1<=b?e.expandUrlAsync(d):Promise.resolve(d)).then(function(f){if(1==b){var g=e.collectDisallowedVarsSync(a);if(0<g.length)throw A().createError('URL variable substitutions in CORS fetches from dynamic URLs (e.g. via amp-bind) require opt-in. Please add data-amp-replace="'+(g.join(" ")+'" to the <')+(a.tagName+"> element. See https://bit.ly/amp-var-subs."));}var h={};a.hasAttribute("credentials")&&(h.credentials=a.getAttribute("credentials"));c&&
(h.cache="reload");return{xhrUrl:f,fetchOpt:h}})};function eb(a,b,c,d){var e={detail:c};Object.assign(e,d);if("function"==typeof a.CustomEvent)return new a.CustomEvent(b,e);a=a.document.createEvent("CustomEvent");a.initCustomEvent(b,!!e.bubbles,!!e.cancelable,c);return a};function fb(a){a=AMP.BaseElement.call(this,a)||this;a.S=void 0;a.aa=new H;return a}ja(fb,AMP.BaseElement);m=fb.prototype;m.getLayoutPriority=function(){return 1};m.isAlwaysFixed=function(){return!0};m.isLayoutSupported=function(){return!0};
m.buildCallback=function(){var a=this;Pa(this.element);this.element.setAttribute("aria-hidden","true");var b=this.element;b.hasAttribute("overridable")&&$a(b).then(function(c){c.addOverridableKey(b.getAttribute("id"))});this.parseAndUpdate();this.element.hasAttribute("src")&&gb(this,!0);this.registerAction("refresh",function(){D(a.element.hasAttribute("src"),'Can\'t refresh <amp-state> without "src" attribute.');gb(a,!1,!0)})};
m.mutatedAttributesCallback=function(a){if(this.getAmpDoc().hasBeenVisible())void 0!==a.src&&this.element.hasAttribute("src")&&gb(this,!1);else{var b=this.M();B().error(b,"ampdoc must be visible before mutation.")}};m.renderOutsideViewport=function(){return!0};m.parseAndUpdate=function(){return void 0===this.S&&(this.S=hb(this),null!==this.S)?ib(this,this.S,!0):S()};
function hb(a){var b=a.element.children;if(0==b.length)return null;var c=a.M();if(1!=b.length)return a.user().error(c,"Should contain exactly one <script> child."),null;var d=b[0];return Xa(d)?ab(d.textContent,function(e){a.user().error(c,"Failed to parse state. Is it valid JSON?",e)}):(a.user().error(c,'State should be in a <script> tag with type="application/json".'),null)}
function jb(a,b,c){var d=a.element,e=a.getAmpDoc(),f=d.getAttribute("src");f=P(La(f)).origin===P(La(e.win.location)).origin||b?2:1;return cb(e,a.element,{urlReplacement:f,refresh:c}).catch(function(g){g=g?eb(a.win,"amp-state.error",F({response:g.response})):null;ua(d,"action").trigger(d,"fetch-error",g,1)})}
function gb(a,b,c){b||(a.aa=new H);var d=a.aa;a.getAmpDoc().whenFirstVisible().then(function(){return jb(a,b,c)}).then(function(e){return ib(a,e,b)}).then(function(){return d.resolve()}).catch(function(e){d.resolve();throw e;})}m.getFetchingPromise=function(){return this.element.hasAttribute("src")?this.aa.promise:S()};
function ib(a,b,c){if(void 0===b||null===b)return S();var d=D(a.element.id,"<amp-state> must have an id.");return $a(a.element).then(function(e){var f=E();f[d]=b;e.setState(f,{skipEval:c,skipAmpState:!c})})}m.M=function(){return"<amp-state> "+(this.element.getAttribute("id")||"<unknown id>")};var kb=/(\S+)(?:\s+(?:(-?\d+(?:\.\d+)?)([a-zA-Z]*)))?\s*(?:,|$)/g;function lb(a){for(var b=[],c;c=kb.exec(a);){var d=c[1],e=void 0,f=void 0;if(c[2]){var g=c[3].toLowerCase();if("w"==g)e=parseInt(c[2],10);else if("x"==g)f=parseFloat(c[2]);else continue}else f=1;b.push({url:d,width:e,dpr:f})}return new mb(b)}
function mb(a){D(0<a.length,"Srcset must have at least one source");this.O=a;for(var b=!1,c=!1,d=0;d<a.length;d++){var e=a[d];b=b||!!e.width;c=c||!!e.dpr}D(!!(b^c),"Srcset must have width or dpr sources, but not both");a.sort(b?nb:rb);this.sa=b}
mb.prototype.select=function(a,b){if(this.sa){b*=a;a=this.O;for(var c=0,d=Infinity,e=Infinity,f=0;f<a.length;f++){var g=a[f].width,h=Math.abs(g-b);if(h<=1.1*d||1.2<b/e)c=f,d=h,e=g;else break}b=c}else{a=this.O;c=0;d=Infinity;for(e=0;e<a.length;e++)if(f=Math.abs(a[e].dpr-b),f<=d)c=e,d=f;else break;b=c}return this.O[b].url};mb.prototype.getUrls=function(){return this.O.map(function(a){return a.url})};
mb.prototype.stringify=function(a){for(var b=[],c=this.O,d=0;d<c.length;d++){var e=c[d],f=e.url;a&&(f=a(f));f=this.sa?f+(" "+e.width+"w"):f+(" "+e.dpr+"x");b.push(f)}return b.join(", ")};function nb(a,b){D(a.width!=b.width,"Duplicate width: %s",a.width);return a.width-b.width}function rb(a,b){D(a.dpr!=b.dpr,"Duplicate dpr: %s",a.dpr);return a.dpr-b.dpr};var sb={"class":{denylistedValueRegex:"(^|\\W)i-amphtml-"},hidden:null,text:null},tb={width:null,height:null},ub={"AMP-AUDIO":{album:null,artist:null,artwork:null,controlsList:null,loop:null,src:{allowedProtocols:{https:!0}},title:null},"AMP-AUTOCOMPLETE":{src:{allowedProtocols:{https:!0}}},"AMP-BASE-CAROUSEL":{"advance-count":null,"auto-advance-count":null,"auto-advance-interval":null,"auto-advance-loops":null,"auto-advance":null,horizontal:null,"initial-index":null,loop:null,"mixed-length":null,
"side-slide-count":null,slide:null,"snap-align":null,"snap-by":null,snap:null,"visible-count":null},"AMP-BRIGHTCOVE":{"data-account":null,"data-embed":null,"data-player":null,"data-player-id":null,"data-playlist-id":null,"data-video-id":null},"AMP-CAROUSEL":{slide:null},"AMP-DATE-PICKER":{max:null,min:null,src:{allowedProtocols:{https:!0}}},"AMP-GOOGLE-DOCUMENT-EMBED":{src:null,title:null},"AMP-IFRAME":{src:null,title:null},"AMP-IMG":{alt:null,attribution:null,src:{allowedProtocols:{data:!0,http:!0,
https:!0}},srcset:{alternativeName:"src"}},"AMP-LIGHTBOX":{open:null},"AMP-LIST":{src:{allowedProtocols:{https:!0}},state:null,"is-layout-container":null},"AMP-SELECTOR":{disabled:null,selected:null},"AMP-STATE":{src:{allowedProtocols:{https:!0}}},"AMP-TIMEAGO":{datetime:null,title:null},"AMP-TWITTER":{"data-tweetid":null},"AMP-VIDEO":{album:null,alt:null,artist:null,artwork:null,attribution:null,controls:null,controlslist:null,loop:null,poster:null,preload:null,src:{allowedProtocols:{https:!0}},
title:null},"AMP-YOUTUBE":{"data-videoid":null},A:{href:{allowedProtocols:{ftp:!0,geo:!0,http:!0,https:!0,mailto:!0,maps:!0,bip:!0,bbmi:!0,chrome:!0,"itms-services":!0,facetime:!0,"fb-me":!0,"fb-messenger":!0,intent:!0,line:!0,skype:!0,sms:!0,snapchat:!0,tel:!0,tg:!0,threema:!0,twitter:!0,viber:!0,webcal:!0,"web+mastodon":!0,wh:!0,whatsapp:!0}}},BUTTON:{disabled:null,type:null,value:null},DETAILS:{open:null},FIELDSET:{disabled:null},IMAGE:{"xlink:href":{allowedProtocols:{http:!0,https:!0}}},INPUT:{accept:null,
accesskey:null,autocomplete:null,checked:null,disabled:null,height:null,inputmode:null,max:null,maxlength:null,min:null,minlength:null,multiple:null,pattern:null,placeholder:null,readonly:null,required:null,selectiondirection:null,size:null,spellcheck:null,step:null,type:{denylistedValueRegex:"(^|\\s)(button|image|)(\\s|$)"},value:null,width:null},OPTION:{disabled:null,label:null,selected:null,value:null},OPTGROUP:{disabled:null,label:null},SECTION:{"data-expand":null,expanded:null},SELECT:{autofocus:null,
disabled:null,multiple:null,required:null,size:null},SOURCE:{src:{allowedProtocols:{https:!0}},type:null},TRACK:{label:null,src:{allowedProtocols:{https:!0}},srclang:null},TEXTAREA:{autocomplete:null,autofocus:null,cols:null,disabled:null,maxlength:null,minlength:null,pattern:null,placeholder:null,readonly:null,required:null,rows:null,selectiondirection:null,selectionend:null,selectionstart:null,spellcheck:null,wrap:null,defaulttext:null}},vb={src:!0,srcset:!0,href:!0,"xlink:href":!0};
function wb(a){this.ua=a}wb.prototype.canBind=function(a,b){return void 0!==xb(this,a,b)};
wb.prototype.isResultValid=function(a,b,c){var d=xb(this,a,b);d&&d.alternativeName&&(d=xb(this,a,d.alternativeName));if(void 0===d)return!1;if(null===d)return!0;if(c&&G(vb,b)){if("srcset"===b){try{var e=lb(c)}catch(h){return A().error("amp-bind","Failed to parse srcset: ",h),!1}var f=e.getUrls()}else f=[c];for(a=0;a<f.length;a++){a:{e=f[a];b=d;if(e){if(/__amp_source_origin/.test(e)){b=!1;break a}if(b=b.allowedProtocols)if(e=/^([^:\/?#.]+):[\s\S]*$/.exec(e),null!==e&&(e=e[1].toLowerCase().trim(),!sa.call(b,
e))){b=!1;break a}}b=!0}if(!b)return!1}}var g=d.denylistedValueRegex;return c&&g&&(new RegExp(g,"i")).test(c)?!1:!0};function xb(a,b,c){if(c.startsWith("aria-"))return null;if(!G(vb,c)||a.ua){var d=G(sb,c);if(void 0!==d)return d;var e=G(tb,c);if(b.startsWith("AMP-")&&void 0!==e)return e;var f=G(ub,b);if(f)return f[c]}};var yb=!1;function zb(a){if(!yb){yb=!0;a=a.body;var b={opacity:1,visibility:"visible",animation:"none"},c;for(c in b){var d=a,e=b[c];var f=d.style;var g=c;if(g.startsWith("--"))f=g;else{R||(R=E());var h=R[g];if(!h){h=g;if(void 0===f[g]){var k=g;k=k.charAt(0).toUpperCase()+k.slice(1);b:{for(var l=0;l<Oa.length;l++){var p=Oa[l]+k;if(void 0!==f[p]){k=p;break b}}k=""}void 0!==f[k]&&(h=k)}R[g]=h}f=h}f&&(f.startsWith("--")?d.style.setProperty(f,e):d.style[f]=e)}}};function U(){this.o=[]}U.prototype.peek=function(){var a=this.o.length;return a?this.o[a-1].item:null};U.prototype.enqueue=function(a,b){if(isNaN(b))throw Error("Priority must not be NaN.");for(var c=-1,d=0,e=this.o.length;d<=e;){c=Math.floor((d+e)/2);if(c===this.o.length)break;if(this.o[c].priority<b)d=c+1;else if(0<c&&this.o[c-1].priority>=b)e=c-1;else break}this.o.splice(c,0,{item:a,priority:b})};U.prototype.forEach=function(a){for(var b=this.o.length;b--;)a(this.o[b].item)};
U.prototype.dequeue=function(){return this.o.length?this.o.pop().item:null};ca.Object.defineProperties(U.prototype,{length:{configurable:!0,enumerable:!0,get:function(){return this.o.length}}});var Ab=/nochunking=1/.test(self.location.hash),Bb=S();function Cb(a,b){if(Ab)Bb.then(b);else{var c=Db,d=L(a),e=M(d);wa(e,d,"chunk",c);K(a,"chunk").run(b,10)}}function V(a){this.state="not_run";this.Z=a}function Eb(a,b){if("run"!=a.state){a.state="run";try{a.Z(b)}catch(c){throw a.ma(),c;}}}V.prototype.M=function(){return this.Z.displayName||this.Z.name};V.prototype.ma=function(){};V.prototype.ka=function(){return!1};V.prototype.qa=function(){return!1};function W(a,b,c){V.call(this,a);this.ga=c}
ja(W,V);W.prototype.ma=function(){zb(self.document)};W.prototype.ka=function(){return this.ga.ampdoc.isVisible()};W.prototype.qa=function(){return this.ga.ha};
function Db(a){var b=this;this.ampdoc=a;this.h=a.win;this.L=new U;this.fa=this.ia.bind(this);this.I=0;this.Ea=!(!this.h.navigator.scheduling||!this.h.navigator.scheduling.isInputPending);this.U=!1;this.va=this.h.document.documentElement.hasAttribute("i-amphtml-no-boilerplate");this.h.addEventListener("message",function(c){"amp-macro-task"==c.data&&b.ia(null)});this.ha=!1;xa(M(a),"viewer").then(function(){b.ha=!0});a.onVisibilityChanged(function(){a.isVisible()&&Fb(b)})}
Db.prototype.run=function(a,b){var c=new V(a);this.L.enqueue(c,b);Fb(this)};Db.prototype.runForStartup=function(a){a=new W(a,this.h,this);this.L.enqueue(a,Number.POSITIVE_INFINITY);Fb(this)};function Gb(a,b){for(var c=a.L.peek();c&&"not_run"!==c.state;)a.L.dequeue(),c=a.L.peek();c&&b&&a.L.dequeue();return c}
Db.prototype.ia=function(a){var b=this,c=Gb(this,!0);if(!c)return this.U=!1,this.I=0,!1;try{var d=Date.now();Eb(c,a)}finally{Bb.then().then().then().then().then().then().then().then().then(function(){b.U=!1;b.I+=Date.now()-d;B().fine("CHUNK",c.M(),"Chunk duration",Date.now()-d,b.I);Fb(b)})}return!0};function Hb(a){a.va&&(a.Ea?a.h.navigator.scheduling.isInputPending():5<a.I)?(a.I=0,Ib(a)):Bb.then(function(){a.fa(null)})}
function Fb(a){if(!a.U){var b=Gb(a);b&&(b.ka()?(a.U=!0,Hb(a)):b.qa()&&a.h.requestIdleCallback?Jb(a.h,a.fa):Ib(a))}}function Ib(a){a.h.postMessage("amp-macro-task","*")}
function Jb(a,b){function c(e){if(15>e.timeRemaining()){var f=2E3-(Date.now()-d);0>=f||e.didTimeout?(B().fine("CHUNK","Timed out",2E3,e.didTimeout),b(e)):(B().fine("CHUNK","Rescheduling with",f,e.timeRemaining()),a.requestIdleCallback(c,{timeout:f}))}else B().fine("CHUNK","Running idle callback with ",15),b(e)}var d=Date.now();a.requestIdleCallback(c,{timeout:2E3})};function Kb(){this.F=E();this.j=null}m=Kb.prototype;m.get=function(a){a=this.F[a];return null==a?null:a};m.whenSignal=function(a){var b=this.j&&this.j[a];if(!b){var c=this.F[a];null!=c?b={promise:"number"==typeof c?Promise.resolve(c):Promise.reject(c)}:(c=new H,b={promise:c.promise,resolve:c.resolve,reject:c.reject});this.j||(this.j=E());this.j[a]=b}return b.promise};
m.signal=function(a,b){if(null==this.F[a]){var c=void 0==b?Date.now():b;this.F[a]=c;(a=this.j&&this.j[a])&&a.resolve&&(a.resolve(c),a.resolve=void 0,a.reject=void 0)}};m.rejectSignal=function(a,b){null==this.F[a]&&(this.F[a]=b,(a=this.j&&this.j[a])&&a.reject&&(a.reject(b),a.promise.catch(function(){}),a.resolve=void 0,a.reject=void 0))};m.reset=function(a){this.F[a]&&delete this.F[a];var b=this.j&&this.j[a];b&&!b.resolve&&delete this.j[a]};function Lb(a,b){function c(){d=0;var g=5E3-(a.Date.now()-e);if(0<g)d=a.setTimeout(c,g);else{var h=f;f=null;b.apply(null,h)}}var d=0,e=0,f=null;return function(g){for(var h=[],k=0;k<arguments.length;++k)h[k-0]=arguments[k];e=a.Date.now();f=h;d||(d=a.setTimeout(c,5E3))}};function Mb(a,b){for(var c=[],d=0,e=0;e<a.length;e++){var f=a[e];b(f,e,a)?c.push(f):(d<e&&(a[d]=f),d++)}d<a.length&&(a.length=d)}function Nb(a,b){for(var c=0;c<a.length;c++)if(b(a[c],c,a))return c;return-1};function Ob(){var a=q().esm?".mjs":".js";var b=y.cdn;return b+"/rtv/"+q().rtvVersion+"/ww"+a};function Pb(a){var b=this;this.h=a;this.Ga=I(a,"xhr");var c=Ob();B().fine("web-worker","Fetching web worker from",c);this.da=null;this.ja=this.Ga.fetchText(c,{ampCors:!1,bypassInterceptorForDev:!1}).then(function(d){return d.text()}).then(function(d){d=d.replace(/^\/\/# sourceMappingURL=.*/,"//# sourceMappingURL="+(c+".map"));d=new a.Blob([d+"\n//# sourceurl="+c],{type:"text/javascript"});var e=a.URL.createObjectURL(d);b.da=new a.Worker(e);b.da.onmessage=b.Da.bind(b)});this.T={};this.xa=0;this.ta=
[a]}function Qb(a,b,c,d){return a.ja.then(function(){return new Promise(function(e,f){var g=a.xa++;a.T[g]={method:b,resolve:e,reject:f};e=d||a.h;f=a.ta.indexOf(e);e=0<=f?f:a.ta.push(e)-1;a.da.postMessage({method:b,args:c,scope:e,id:g})})})}Pb.prototype.Da=function(a){var b=a.data;a=b.method;var c=b.returnValue;b=b.id;var d=this.T[b];d?(d.resolve(c),delete this.T[b]):B().error("web-worker","Received unexpected message ("+a+", "+b+") from worker.")};
Pb.prototype.hasPendingMessages=function(){return 0<Object.keys(this.T).length};Pb.prototype.Ha=function(){return this.ja};function Rb(a){var b=a.documentElement;return["\u26a14email","amp4email"].some(function(c){return b.hasAttribute(c)})};function Sb(){var a=Tb();return function(b){return setTimeout(b,a())}}function Tb(){var a=0;return function(){var b=Math.pow(1.5,a++);var c=b*(c||.3)*Math.random();.5<Math.random()&&(c*=-1);b+=c;return 1E3*b}};var X=self.__AMP_ERRORS||[];self.__AMP_ERRORS=X;function Ub(a){Ub=Sb();return Ub(a)}function Vb(a){try{return JSON.stringify(a)}catch(b){return String(a)}}var Wb;
function Y(a,b){try{if(a)if(void 0!==a.message)a=ra(a);else{var c=a;a=Error(Vb(c));a.origError=c}else a=Error("Unknown error");if(!a.reported){a.reported=!0;var d=b||a.associatedElement;d&&d.classList&&(d.classList.add("i-amphtml-error"),q().development&&(d.classList.add("i-amphtml-element-error"),d.setAttribute("error-message",a.message)));if(self.console&&(0<=a.message.indexOf("\u200b\u200b\u200b")||!a.expected)){var e=console.error||console.log;a.messageArray?e.apply(console,a.messageArray):d?
e.call(console,a.message,d):e.call(console,a.message)}d&&d.Aa&&d.Aa("amp:error",a.message);Xb.call(self,void 0,void 0,void 0,void 0,a)}}catch(f){setTimeout(function(){throw f;})}}function Xb(a,b,c,d,e){var f=this;!this||!this.document||e&&e.expected||zb(this.document);if(!q().development){var g=!1;try{g=Yb()}catch(k){}if(!(g&&.01<Math.random())){var h=Zb(a,b,c,d,e,g);h&&Ub(function(){try{return $b(f,h).catch(function(){})}catch(k){}})}}}
function $b(a,b){return b.pt&&.9>Math.random()?S():ac(a,b).then(function(c){if(!c){var d=new XMLHttpRequest;d.open("POST",.1>Math.random()?y.betaErrorReporting:y.errorReporting,!0);d.send(JSON.stringify(b))}})}
function ac(a,b){var c=I(a,"ampdoc");if(!c.isSingleDoc())return Promise.resolve(!1);var d=c.getSingleDoc();if(!d.getRootNode().documentElement.hasAttribute("report-errors-to-viewer"))return Promise.resolve(!1);var e=K(d,"viewer");return e.hasCapability("errorReporter")?e.isTrustedViewer().then(function(f){if(!f)return!1;e.sendMessage("error",F({m:b.m,a:b.a,s:b.s,el:b.el,ex:b.ex,v:b.v,pt:b.pt,jse:b.jse}));return!0}):Promise.resolve(!1)}
function Zb(a,b,c,d,e,f){var g=a;e&&(g=e.message?e.message:String(e));g||(g="Unknown error");a=g;var h=!(!e||!e.expected);if(!/_reported_/.test(a)&&"CANCELLED"!=a){var k=!(self&&self.window),l=Math.random();if(-1!=a.indexOf("Failed to load:")||"Script error."==a||k)if(h=!0,.001<l)return;var p=0<=a.indexOf("\u200b\u200b\u200b");if(!(p&&.1<l)){g=Object.create(null);g.v=q().rtvVersion;g.noAmp=f?"1":"0";g.m=a.replace("\u200b\u200b\u200b","");g.a=p?"1":"0";g.ex=h?"1":"0";g.dw=k?"1":"0";var n="1p";self.context&&
self.context.location?(g["3p"]="1",n="3p"):q().runtime&&(n=q().runtime);g.rt=n;"inabox"===n&&(g.adid=q().a4aId);f=self;g.ca=f.AMP_CONFIG&&f.AMP_CONFIG.canary?"1":"0";f=self;g.bt=f.AMP_CONFIG&&f.AMP_CONFIG.type?f.AMP_CONFIG.type:"unknown";self.location.ancestorOrigins&&self.location.ancestorOrigins[0]&&(g.or=self.location.ancestorOrigins[0]);self.viewerState&&(g.vs=self.viewerState);self.parent&&self.parent!=self&&(g.iem="1");if(self.AMP&&self.AMP.viewer){var t=self.AMP.viewer.getResolvedViewerUrl(),
C=self.AMP.viewer.maybeGetMessagingOrigin();t&&(g.rvu=t);C&&(g.mso=C)}Wb||(Wb=bc());g.jse=Wb;var w=[];f=self.__AMP__EXPERIMENT_TOGGLES||null;for(var u in f)w.push(u+"="+(f[u]?"1":"0"));g.exps=w.join(",");e?(g.el=e.associatedElement?e.associatedElement.tagName:"u",e.args&&(g.args=JSON.stringify(e.args)),p||e.ignoreStack||!e.stack||(g.s=e.stack),e.message&&(e.message+=" _reported_")):(g.f=b||"",g.l=c||"",g.c=d||"");g.r=self.document?self.document.referrer:"";g.ae=X.join(",");g.fr=self.location.originalHash||
self.location.hash;"production"===g.bt&&(g.pt="1");b=a;25<=X.length&&X.splice(0,X.length-25+1);X.push(b);return g}}}function Yb(){var a=self;if(!a.document)return!1;a=a.document.querySelectorAll("script[src]");for(var b=0;b<a.length;b++)if(!Q(a[b].src.toLowerCase()))return!0;return!1}
function bc(){function a(){}a.prototype.t=function(){throw Error("message");};var b=new a;try{b.t()}catch(d){b=d.stack;if(b.startsWith("t@"))return"Safari";if(-1<b.indexOf(".prototype.t@"))return"Firefox";var c=b.split("\n").pop();if(/\bat .* \(/i.test(c))return"IE";if(b.startsWith("Error: message"))return"Chrome"}return"unknown"};function cc(a,b,c){var d=self.location;Na(c);var e=Q(d),f=P(La(d));if("href"==b&&!c.startsWith("#"))return Ma(c,f);if("src"==b)return"amp-img"==a?dc(c,f,e):Ma(c,f);if("srcset"==b){try{var g=lb(c)}catch(h){return A().error("URL-REWRITE","Failed to parse srcset: ",h),c}return g.stringify(function(h){return dc(h,f,e)})}return c}
function dc(a,b,c){a=P(Ma(a,b));return"data:"==a.protocol||Q(a)||!c?a.href:y.cdn+"/i/"+("https:"==a.protocol?"s/":"")+encodeURIComponent(a.host)+a.pathname+(a.search||"")+(a.hash||"")};var ec=/^(i?-)?amp(html)?-/,fc={INPUT:{checked:!0,value:!0},OPTION:{selected:!0},TEXTAREA:{text:!0,disabled:!0}},gc=E({"AMP-CAROUSEL":["slide"],"AMP-LIST":["is-layout-container"],"AMP-SELECTOR":["selected"]}),hc=["AMP-LIST"];
function ic(a){var b=this;this.ampdoc=a;this.J=this.h=a.win;this.Y=[];this.Ba=Lb(this.h,function(){b.Y.length=0});this.H=[];this.D=E();this.$=K(a,"history");this.na=[];this.K=1E3;this.la=K(a,"mutator");this.B=E();this.Fa=J(this.h,"timer");this.ra=null;this.W=K(this.ampdoc,"viewer");this.W.onMessageRespond("premutate",this.Ca.bind(this));this.oa=a.whenFirstVisible().then(function(){return a.whenReady().then(function(){return a.getRootNode()})});this.N=this.oa.then(function(d){return jc(b,d)});this.ea=
new H;this.V=null;this.pa=new Kb;var c=self.AMP;c.printState=c.printState||this.za.bind(this);c.setState=c.setState||function(d){return b.setState(d)};c.eval=c.eval||this.ya.bind(this)}m=ic.prototype;m.signals=function(){return this.pa};
m.setState=function(a,b){var c=this,d=b=void 0===b?{}:b;B().info("amp-bind","setState (init=%s):",d.skipEval,a);try{ta(this.B,a)}catch(e){A().error("amp-bind","Failed to merge result from AMP.setState().",e)}return d.skipEval?S():this.V=this.N.then(function(){return kc(c)}).then(function(e){return lc(c,e,{skipAmpState:d.skipAmpState,constrain:d.constrain})})};
m.invoke=function(a){var b=a.args,c=a.event,d=a.method,e=a.sequenceId,f=a.tagOrTarget;if(this.Y.includes(e))return A().error("amp-bind","One state action allowed per event."),S();this.Y.push(e);this.Ba();if(b=b.__AMP_OBJECT_STRING__){this.K=Math.min(2E3,Math.max(1E3,this.K+500));this.pa.signal("FIRST_MUTATE");var g={};c&&c.detail&&(g.event=c.detail);switch(d){case "setState":return this.setStateWithExpression(b,g);case "pushState":return this.pushStateWithExpression(b,g);default:return Promise.reject(B().createError("Unrecognized method: %s.%s",
f,d))}}else A().error("AMP-BIND","Please use the object-literal syntax, e.g. \"AMP.setState({foo: 'bar'})\" instead of \"AMP.setState(foo='bar')\".");return S()};m.setStateWithExpression=function(a,b){var c=this;return mc(this,a,b).then(function(d){return nc(c,d)})};m.setStateWithObject=function(a){return(a=oc(a))?nc(this,a):Promise.reject("Invalid state")};
function nc(a,b){B().info("amp-bind","setState:",b);a.V=a.setState(b).then(function(){return pc(a)}).then(function(c){c&&a.$.replace(c)});return a.V}m.pushStateWithExpression=function(a,b){var c=this;B().info("amp-bind","pushState:",a);return mc(this,a,b).then(function(d){function e(){return c.setState(f)}var f=E();Object.keys(d).forEach(function(g){f[g]=oc(c.B[g])});return c.setState(d).then(function(){return pc(c)}).then(function(g){c.$.push(e,g)})})};
function pc(a){var b=F({data:F({"amp-bind":a.B}),title:a.J.document.title});return a.W.isEmbedded()?a.W.isTrustedViewer().then(function(c){return c?b:null}):Promise.resolve(b)}m.rescan=function(a,b,c){var d=this,e=c=void 0===c?{}:c;return(e.fast?this.ea.promise:this.N).then(function(){return d.Fa.timeoutPromise(e.timeout||2E3,qc(d,a,b,e),"Timed out waiting for amp-bind to rescan.")})};
function qc(a,b,c,d){B().info("amp-bind","rescan: ",b,c,d);return(d.fast?rc(a,b,c):sc(a,b,c)).then(function(){if(d.update)return kc(a).then(function(e){return lc(a,e,{constrain:b,evaluateOnly:"evaluate"===d.update})})})}
function rc(a,b,c){var d=tc(a,c),e=[],f=b.filter(function(h){return h.hasAttribute("i-amphtml-binding")});b.forEach(function(h){h=h.querySelectorAll("[i-amphtml-binding]");Array.prototype.push.apply(f,h)});var g=a.K-a.numberOfBindings();for(b=0;b<f.length&&!uc(a,f[b],g-e.length,e);b++);d.then(function(h){B().info("amp-bind","rescan.fast: delta=%s, total=%s",e.length-h,a.numberOfBindings())});return 0<e.length?vc(a,e):S()}
m.getState=function(a){a=a?T(this.B,a):void 0;return v(a)||Array.isArray(a)?oc(a):a};m.getStateAsync=function(a){var b=this,c=/^[^.]*/.exec(a)[0];return this.oa.then(function(d){var e=d.querySelector("#"+String(c).replace(Sa,Ta));if(!e)throw Error("#"+c+" does not exist.");return Ya(e).then(function(f){return f.getImpl(!0)}).then(function(f){return f.getFetchingPromise()}).catch(function(){}).then(function(){return b.getState(a)})})};
m.getStateValue=function(a){a=T(this.B,a);return void 0===a||null===a?null:v(a)||Array.isArray(a)?JSON.stringify(a):String(a)};
function jc(a,b){var c=!Rb(a.J.document);a.ra=new wb(c);return Z(a,"bind.init",[c]).then(function(){return Promise.all([wc(a).then(function(){return a.ea.resolve()}),xc(a,[b])])}).then(function(){b.addEventListener("amp:dom-update",function(d){return yc(a,d)})}).then(function(){var d=b.querySelectorAll("AMP-STATE"),e=r(d).map(function(f){return Ya(f).then(function(){return f.getImpl(!1)}).then(function(g){return g.parseAndUpdate()})});return Promise.all(e)}).then(function(){a.W.sendMessage("bindReady",
void 0);if(q().development)return kc(a).then(function(d){return zc(a,d)})})}m.numberOfBindings=function(){return this.H.reduce(function(a,b){return a+b.boundProperties.length},0)};m.Ka=function(a){this.K=a};m.Ia=function(){return this.$};
m.Ca=function(a){var b=this,c=[];return this.N.then(function(){Object.keys(a.state).forEach(function(d){b.na.includes(d)||(delete a.state[d],c.push(d))});0<c.length&&A().warn("amp-bind","Some state keys could not be premutated because they are missing the overridable attribute: "+c.join(", "));return b.setState(a.state)})};m.addOverridableKey=function(a){this.na.push(a)};
function wc(a){var b=a.ampdoc.getBody().querySelectorAll("AMP-BIND-MACRO"),c=[];Wa(b,function(d){var e=(d.getAttribute("arguments")||"").split(",").map(function(f){return f.trim()});c.push({id:d.getAttribute("id"),argumentNames:e,expressionString:d.getAttribute("expression")})});return 0==c.length?Promise.resolve(0):Z(a,"bind.addMacros",[c]).then(function(d){d.forEach(function(e,f){Ac(e,"amp-bind: Parsing amp-bind-macro failed.",b[f])});return c.length})}
function xc(a,b){if(!b.length)return Promise.resolve(0);var c=b.map(function(d){var e=a.K-a.numberOfBindings();return Bc(a,d,e).then(function(f){var g=f.bindings;f.limitExceeded&&B().expectedError("amp-bind","Maximum number of bindings reached (%s). Additional elements with bindings will be ignored.",a.K);return g})});return Promise.all(c).then(function(d){d=Array.prototype.concat.apply([],d);return 0<d.length?vc(a,d):0})}
function vc(a,b){return Z(a,"bind.addBindings",[b]).then(function(c){Object.keys(c).forEach(function(d){var e=a.D[d];0<e.length&&Ac(c[d],'amp-bind: Expression compile error in "'+d+'".',e[0])});return b.length})}
function tc(a,b){if(!b.length)return Promise.resolve(0);Mb(a.H,function(g){for(var h=0;h<b.length;h++)if(b[h].contains(g.element))return!0;return!1});var c=[],d;for(d in a.D){var e=a.D[d];Mb(e,function(g){for(var h=0;h<b.length;h++)if(b[h].contains(g))return!0;return!1});0==e.length&&(c.push(d),delete a.D[d])}var f=c.length;return 0<f?Z(a,"bind.removeBindingsWithExpressionStrings",[c]).then(function(){return f}):Promise.resolve(0)}
function Bc(a,b,c){function d(){var h=f.currentNode;if(!h)return!0;if(h.nodeType!==Node.ELEMENT_NODE)return!f.nextNode();uc(a,h,c-e.length,e)&&(g=!0);if(hc.includes(h.nodeName))a:{for(h=f.currentNode;h;h=f.parentNode())if(h=f.nextSibling())break a;h=null}else h=f.nextNode();return!h||g}var e=[],f=(b.nodeType==Node.DOCUMENT_NODE?b:b.ownerDocument).createTreeWalker(b,NodeFilter.SHOW_ELEMENT,null,!1),g=!1;return new Promise(function(h){function k(l){var p=!1;if(l&&!l.didTimeout)for(;1<l.timeRemaining()&&
!p;)p=d();else for(l=0;250>l&&!p;l++)p=d();p?h({bindings:e,limitExceeded:g}):Cb(a.ampdoc,k)}Cb(a.ampdoc,k)})}function uc(a,b,c,d){var e=!1,f=Cc(a,b);f.length>c&&(f.length=c,e=!0);0<f.length&&a.H.push({element:b,boundProperties:f});var g=b.tagName;f.forEach(function(h){var k=h.expressionString;d.push({tagName:g,property:h.property,expressionString:k});a.D[k]||(a.D[k]=[]);a.D[k].push(b)});return e}
function Cc(a,b){for(var c=[],d=b.attributes,e=0,f=d.length;e<f;e++){a:{var g=void 0,h=a,k=d[e];var l=b;var p=l.tagName,n=k.name;if(2<n.length&&"["===n[0]&&"]"===n[n.length-1])g=n.substr(1,n.length-2);else if(n.startsWith("data-amp-bind-")&&(g=n.substr(14),l.hasAttribute("["+g+"]"))){l=null;break a}if(g){if(h.ra.canBind(p,g)){l={property:g,expressionString:k.value};break a}g=A().createError("%s: Binding to [%s] on <%s> is not allowed.","amp-bind",g,p);Y(g,l)}l=null}l&&c.push(l)}return c}
function mc(a,b,c){return a.N.then(function(){Object.assign(c,a.B);return Z(a,"bind.evaluateExpression",[b,c])}).then(function(d){var e=d.result;if(d=d.error)throw Ac(d,"amp-bind: Expression eval failed.");return e})}
function kc(a){return Z(a,"bind.evaluateBindings",[a.B]).then(function(b){var c=b.results,d=b.errors;Object.keys(d).forEach(function(e){var f=a.D[e];if(0<f.length){var g=d[e],h=A().createError('%s: Expression evaluation error in "%s". %s',"amp-bind",e,g.message);h.stack=g.stack;Y(h,f[0])}});B().info("amp-bind","evaluation:",c);return c})}
function zc(a,b){var c=void 0===c?!0:c;var d={};a.H.forEach(function(e){var f=e.element;e.boundProperties.forEach(function(g){var h=b[g.expressionString];if(void 0!==h){var k=g.property,l=gc[f.tagName];if(l&&l.includes(k))h=null;else{switch(k){case "text":k=f.textContent;h=String(h);l=k.trim()===h.trim();break;case "class":k=[];for(l=0;l<f.classList.length;l++){var p=f.classList[l];ec.test(p)||k.push(p)}p=[];Array.isArray(h)?p=h:"string"===typeof h?(l=h.trim(),0<l.length&&(p=l.split(" "))):(l=A().createError('%s: "%s" is not a valid result for [class].',
"amp-bind",h),Y(l,f));b:{l=k;var n=p;if(l.length!==n.length)l=!1;else{p=(Array.isArray(l)?l:r(l)).sort();n=(Array.isArray(n)?n:r(n)).sort();for(var t=0;t<l.length;t++)if(p[t]!==n[t]){l=!1;break b}l=!0}}break;default:k=f.getAttribute(k),l=!0===h?""===k:!1===h?null===k:"number"===typeof h?Number(k)===h:k===h}h=l?null:{expected:h,actual:k}}var C=h;if(C){h=f.tagName;k=g.property;g=g.expressionString;l=C.expected;var w=C.actual;d[h+"["+k+"]"+l+":"+w]=!0;c&&A().warn("amp-bind","Default value ("+w+") does not match first result ("+
(l+") for <"+h+" ["+k+']="')+(g+'">. We recommend writing expressions with matching default values, but this can be safely ignored if intentional.'))}}})});return Object.keys(d)}function Dc(a,b){var c=[];a.forEach(function(d){var e=d.previousResult,f=b[d.expressionString];void 0===f||bb(f,e)||(d.previousResult=f,c.push({boundProperty:d,newValue:f}))});return c}
function lc(a,b,c){var d=[];a.H.forEach(function(e){if(!c.skipAmpState||"AMP-STATE"!==e.element.tagName)if(!c.constrain||c.constrain.some(function(h){return h.contains(e.element)})){var f=e.element,g=Dc(e.boundProperties,b);c.evaluateOnly||d.push(Ec(a,f,g))}});return Promise.all(d)}
function Ec(a,b,c){return 0===c.length?S():a.la.mutateElement(b,function(){var d=E(),e,f;c.forEach(function(h){var k=h.boundProperty,l=h.newValue,p=k.property;a:{k=k.property;var n=b.tagName;switch(k){case "defaulttext":b.textContent=String(l);break;case "text":k=String(l);"TITLE"===n&&b.parentNode===a.J.document.head&&(a.J.document.title=k);"TEXTAREA"===n?b.value=k:b.textContent=k;break;case "class":k=[];for(n=0;n<b.classList.length;n++){var t=b.classList[n];ec.test(t)&&k.push(t)}Array.isArray(l)||
"string"===typeof l?b.setAttribute("class",k.concat(l).join(" ")):null===l?b.setAttribute("class",k.join(" ")):(k=A().createError('%s: "%s" is not a valid result for [class].',"amp-bind",l),Y(k,b));break;default:var C="INPUT"===n&&k in b,w=b.getAttribute(k);n=!1;if("boolean"===typeof l){if(C&&b[k]!==l&&(b[k]=l,n=!0),l&&""!==w?(b.setAttribute(k,""),n=!0):l||null===w||(b.removeAttribute(k),n=!0),n&&"OPTION"===b.tagName&&"selected"===k&&l&&I(a.h,"platform").isSafari()&&(t=Va(b,"select"))){var u=r(t.options).indexOf(b);
0<=u&&(t.selectedIndex=u)}}else if("object"===typeof l&&null!==l)n=!0;else if(l!==w)b:{w=String(l);try{t=b.tagName.toLowerCase();u=k.toLowerCase();var Ca="src"==u||"href"==u||"xlink:href"==u||"srcset"==u?cc(t,u,w):w;if(Q(self.location)&&"a"===t&&"href"===u){var ob=b.getAttribute(u),pb="#"===Ca[0],qb=ob&&"#"===ob[0];pb&&!qb?(b.__AMP_ORIGINAL_TARGET_VALUE_||(b.__AMP_ORIGINAL_TARGET_VALUE_=b.getAttribute("target")),b.removeAttribute("target")):qb&&!pb&&b.setAttribute("target",b.__AMP_ORIGINAL_TARGET_VALUE_||
"_top")}C&&(b[u]=Ca);b.setAttribute(u,Ca);n=!0;break b}catch(Fc){n=A().createError('%s: "%s" is not a valid result for [%]',"amp-bind",w,k,Fc),Y(n,b)}n=!1}if(n){k={name:k,value:l};break a}}k=null}var Da=k;Da&&(d[Da.name]=Da.value,"width"==p?e="number"===typeof l&&isFinite(l)?Number(l):e:"height"==p&&(f="number"===typeof l&&isFinite(l)?Number(l):f));(l=fc[b.tagName])&&l[p]&&(p="OPTION"===b.tagName?Va(b,"SELECT"):b)&&(l=eb(a.J,"amp:form-value-change",null,{bubbles:!0}),p.dispatchEvent(l))});void 0===
e&&void 0===f||a.la.forceChangeSize(b,f,e);if("function"===typeof b.mutatedAttributesCallback)try{b.mutatedAttributesCallback(d)}catch(h){var g=A().createError("%s: Applying expression results (%s) failed with error,","amp-bind",JSON.stringify(d),h);Y(g,b)}})}function yc(a,b){b=b.target;var c=b.parentNode;c&&hc.includes(c.nodeName)||(B().info("amp-bind","dom_update:",b),sc(a,[b],[b],"dom_update.end").then(function(){}))}
function sc(a,b,c,d){var e=void 0===d?"rescan.slow":d,f=0;return tc(a,c).then(function(g){f=g;return xc(a,b)}).then(function(g){B().info("amp-bind","%s: delta=%s, total=%s",e,g-f,a.numberOfBindings())})}function Z(a,b,c){var d=a.h;a=a.J;if(d.Worker){var e=d;e=e.__AMP_TOP||(e.__AMP_TOP=e);wa(e,e,"amp-worker",Pb);b=Qb(I(d,"amp-worker"),b,c||[],a)}else b=Promise.reject("Worker not supported in window.");return b}
function Ac(a,b,c){b=A().createError("%s %s",b,a.message);b.stack=a.stack;Y(b,c);return b}function oc(a){if(void 0===a)return null;try{return JSON.parse(JSON.stringify(a))}catch(b){B().error("amp-bind","Failed to copy JSON ("+a+") with error: "+b)}return null}
m.za=function(a){if(a)if("string"==typeof a){var b=T(this.B,a);A().info("amp-bind",b)}else a.nodeType==Node.ELEMENT_NODE?(b=A().assertElement(a),Gc(this,b)):A().info("amp-bind",'Invalid argument. Pass a JSON expression or an element instead e.g. AMP.printState("foo.bar") or AMP.printState($0) after selecting an element.');else A().info("amp-bind",this.B)};
function Gc(a,b){var c=Nb(a.H,function(f){return f.element==b});if(0>c)A().info("amp-bind","Element has no bindings:",b);else{var d=[],e=a.H[c].boundProperties;e.forEach(function(f){d.push(mc(a,f.expressionString,a.B))});Promise.all(d).then(function(f){var g=E();e.forEach(function(h,k){g[h.property]=f[k]});A().info("amp-bind",g)})}}m.ya=function(a){mc(this,a,this.B).then(function(b){A().info("amp-bind",b)})};m.Ja=function(){return this.N};m.La=function(){return this.V};(function(a){a.registerServiceForDoc("bind",ic);a.registerElement("amp-state",fb);a.registerElement("amp-bind-macro",Qa)})(self.AMP);
})});

//# sourceMappingURL=amp-bind-0.1.js.map
