#!/bin/bash
if [ `id -u` = 0 ] ; then
	SCRIPT_HOME="$( cd "$( dirname "$0" )" && pwd )" 
	echo copying rules file
	cp $SCRIPT_HOME/*.rules /etc/udev/rules.d
	echo reloading udev rules
	udevadm control --reload-rules	
else
	echo This script must be run as sudo        
fi